#ifndef QTCOMPRESSGLOBAL_H
#define QTCOMPRESSGLOBAL_H

#include <qglobal.h>

QT_BEGIN_NAMESPACE

#if defined(QT_BUILD_QTCOMPRESS_LIB)
#define QTCOMPRESS_EXPORT Q_DECL_EXPORT
#else
#define QTCOMPRESS_EXPORT Q_DECL_IMPORT
#endif

QT_END_NAMESPACE

#endif // QTCOMPRESSGLOBAL_H
